repos:
  - hooks:
      - id: ruff
        name: ruff
    repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241

  - hooks:
      - id: black
        args:
          - "--check"
    rev: 22.3.0
    repo: https://github.com/psf/black

  - hooks:
      - id: isort
        name: isort (python)
        args:
          - "--check-only"
          - "--profile=black"
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
